#!/bin/bash
#DDDDD的值替换成自己的用户名,upass替换为密码
   if [ $1 == 4 ]
   then
      curl -s >ipv4.txt -d"DDDDD=S201398563&upass=123412&v46s=1&v6ip=&f4serip=172.30.201.2&0MKKey=" https://lgn.bjut.edu.cn/
      if [ $? -eq 0 ]
      then
         echo "ipv4登录成功"
	  fi
   elif [ $1 == 6 ]
   then
      curl -s >ipv6.txt -d"DDDDD=S201761395&upass=liu1112&v46s=2&v6ip=&f4serip=172.30.201.2&0MKKey=" https://lgn.bjut.edu.cn/
      if [ $? -eq 0 ]
      then
	     echo "ipv6登录成功"
	  fi
   elif  [ $1 == 0 ]
   then 
      curl -s  >logout.txt https://lgn.bjut.edu.cn/F.htm
	  if [ $? -eq 0 ]
	  then 
	      echo "退出成功"
	  fi 

   else
      echo "登录失败"
   fi
